### ISSUE TITLE
Missing logo

### ISSUE THREAD

**Issue by kongsted** [xmltv-se/channel-logos#1]
Hi,
Just a minor "issue". :)
The logo for "hd.tv2.dk" is missing.
Could just be a copy of "https://chanlogos.xmltv.se/tv2.dk.png"
//Kongsted

**Comment by jnylen** [comment]
@kongsted Feel free to do a Pull Request with an SVG of the logo. Just name it the same in the `vector/` folder.

**Comment by kongsted** [comment]
I have tried to add the missing logos (found one more).
Hope it will work (it's first time I'm trying to update a repo on GitHub :) )
