### ISSUE TITLE
BunnyCDN Domain suspended or not configured

### ISSUE THREAD

**Issue by karbowiak** [xmltv-se/channel-logos#4]
https://chanlogos.xmltv.se/
and
https://logos.xmltv.se/

Both show as suspended and/or not configured :(

**Comment by jnylen** [comment]
Hi @karbowiak,
These are not coming back. They have been abused a long time by illegal iptv services and we can no longer support this.

We will keep this repository up to date when we can but we won't host the files on our side.

**Comment by karbowiak** [comment]
@jnylen ah, that's a bummer to hear - but alright - i'll sort something out 😄 

Was going to use it for TVHeadEnd and my HDHomeRun setup (Spent like 8hours in the weekend getting Oscam to understand how to decode channels using a Viasat card.. what a fucking pain)
